name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: auto create makefile
        run: automake
      - name: build application
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
